# foundry.toml

[profile.default]
src = "contracts"
out = "artifacts"
libs = ["lib"]
test = "test"
cache_path = "cache"
solc-version = "0.8.20"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
